AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  ec2-start lambda
  ec2-stop lambda

  Sample SAM Template for ec2-stop-lambda and ec2-stop-lambda functions

# More info about Globals: https://github.com/awslabs/serverless-application-model/blob/master/docs/globals.rst
Globals:
  Function:
    Timeout: 60
    Tags:
      owner: anurag.mathur

Resources:
  ec2StopLambdaFunction:
    Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    Properties:
      Policies:
        - Version: '2012-10-17'
          Statement:
            - Effect: Allow
              Action:
                - logs:CreateLogGroup
              Resource: !Sub 'arn:aws:logs:us-east-1:${AWS::AccountId}:*'
            - Effect: Allow
              Action:
                - logs:CreateLogStream
                - logs:PutLogEvents
              Resource: !Sub 'arn:aws:logs:us-east-1:${AWS::AccountId}:log-group:/aws/lambda/ec2schedule:*'
            - Effect: Allow
              Action:
                - ec2:StartInstances
                - ec2:StopInstances
              Resource: !Sub 'arn:aws:ec2:ap-southeast-2:${AWS::AccountId}:instance/*'
            - Effect: Allow
              Action:
                - ec2:Describe*
              Resource: '*'
      Handler: ec2_stop/app.lambda_handler
      Runtime: python3.7
      #Role: arn:aws:iam::${AWS::AccountId}:role/service-role/ec2schedule-role-zp4031b8
  ec2StartLambdaFunction:
    Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    Properties:
      Policies:
        - Version: '2012-10-17'
          Statement:
            - Effect: Allow
              Action:
                - logs:CreateLogGroup
              Resource: !Sub 'arn:aws:logs:us-east-1:${AWS::AccountId}:*'
            - Effect: Allow
              Action:
                - logs:CreateLogStream
                - logs:PutLogEvents
              Resource: !Sub 'arn:aws:logs:us-east-1:${AWS::AccountId}:log-group:/aws/lambda/ec2schedule:*'
            - Effect: Allow
              Action:
                - ec2:StartInstances
                - ec2:StopInstances
              Resource: !Sub 'arn:aws:ec2:ap-southeast-2:${AWS::AccountId}:instance/*'
            - Effect: Allow
              Action:
                - ec2:Describe*
              Resource: '*'
      Handler: ec2_start/app.lambda_handler
      Runtime: python3.7
      #Role: arn:aws:iam::${AWS::AccountId}:role/service-role/ec2schedule-role-zp4031b8
Outputs:
  # ServerlessRestApi is an implicit API created out of Events key under Serverless::Function
  # Find out more about other implicit resources you can reference within SAM
  # https://github.com/awslabs/serverless-application-model/blob/master/docs/internals/generated_resources.rst#api
  ec2StopLambdaFunction:
    Description: "EC2 Stop Lambda Function ARN"
    Value: !GetAtt ec2StopLambdaFunction.Arn
  ec2StartLambdaFunction:
    Description: "EC2 Start Lambda Function ARN"
    Value: !GetAtt ec2StartLambdaFunction.Arn
